package com.src.model;

//Records are immutable data objects
//Requires only field type and name
//AllArgsConstructor, equals, hashCode, toString are generated by the Compiler
public record NewPerson(String name, String address) {}
